development:
  adapter: postgresql
  database: venezia_unica_dev
  username: root
  password: root
  host: localhost
  encoding: utf8

test:
  adapter: postgresql
  database: venezia_unica_test
  username: root
  password: root
  host: localhost
  encoding: utf8

production:
  adapter: postgresql
  database: venezia_unica_prod
  encoding: utf8
